### ISSUE TITLE
Deploy Documentation

### ISSUE THREAD

**Issue by cdeln** [cdeln/cpp_enum_set#3]
Add feature for deploying documentation generated using Doxygen from the master branch to GitHub Pages.

**Comment by friendlyanon** [comment]
[peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) looks like the ideal action for deploying to a `gh-pages` branch. As explained in the [cmake-init docs](https://github.com/friendlyanon/cmake-init#doxygen), the `docs` target will output to the `<binary-dir>/docs/html` by default and it's controlled by the `DOXYGEN_OUTPUT_DIRECTORY` variable.

**Comment by cdeln** [comment]
Sounds perfect!

**Comment by friendlyanon** [comment]
I have released 0.14.0 of cmake-init with automatic documentation deployment set up. You can see my commit history and the example repositories for what this took.

**Comment by cdeln** [comment]
Cool! I am quite busy atm, if you want to grab this please go ahead! I am still very new to github issue handling, not sure if you can assign yourself to it, then just leave a comment so that we don't do duplicate work. Otherwise I can take a look at this next week probably.

**Comment by friendlyanon** [comment]
I'm quite busy myself as well, but wanted to let you know that the minimum required Python version for m.css's script is [Python 3.6](https://mcss.mosra.cz/documentation/doxygen/#basic-usage).

**Comment by cdeln** [comment]
Good to know, then we can check Python_VERSION_MAJOR and Python_VERSION_MINOR result variables after finding python to enforce this

**Comment by friendlyanon** [comment]
The second argument to [`find_package`](https://cmake.org/cmake/help/latest/command/find_package.html) is a version specifier.

**Comment by cdeln** [comment]
Even better! Will probably take a look at this tonight
