### ISSUE TITLE
Generate code coverage report locally

### ISSUE THREAD

**Issue by cdeln** [cdeln/cpp_enum_set#4]
Expose code coverage generation as a cmake target so that developers can generate it locally, without having to push and get code coverage through codecov.io .
Follow the steps used in the CI.

**Comment by cdeln** [comment]
It does not have to be cross platform initially, as long as it works on a "ubuntu-like" environment such as in the CI.

**Comment by friendlyanon** [comment]
What'd be the best way to locally generate a coverage report? For codecov, lcov can generate the gcov style document from the output of the tests, but I have not used that locally, so I'm not sure. While CTest has coverage support, it omits some information that gcov generates and is mainly usable for CDash.

I assume that for local coverage report a HTML document would be the most ideal? I think lcov can generate that as well.

**Comment by cdeln** [comment]
Yes, a HTML doc is ideal. I would expect it to look like the [lcov demo page](http://ltp.sourceforge.net/coverage/lcov/output/index.html)

**Comment by friendlyanon** [comment]
I have experimented with things and I think you can patch things up based on this commit https://github.com/friendlyanon/cmake-init/commit/923c55eb1358f575fc1cd731418e3e8808f297e9

**Comment by cdeln** [comment]
Nice! If you have time please incorporate the necessary changes here as well.
Otherwise I will copy and paste from your changes when I can later.
